apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-rollout-bluegreen.fullname" . }}-preview
  labels:
    {{- include "test-rollout-bluegreen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test-rollout-bluegreen.selectorLabels" . | nindent 4 }}
